name: Test Workflow

on:
  push:
    paths:
      - '**'  # This matches any file in the repository

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test file change detection
        run: echo "A file has been changed and pushed to the repository!"
